# Use DecapBridge PKCE auth since Netlify Identity was deprecated 2025
backend:
  name: git-gateway
  repo: taraxvoid/queeromaha
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/bc97b76f-9d17-419f-b270-59b5fb34dd05/pkce
  auth_token_endpoint: /sites/bc97b76f-9d17-419f-b270-59b5fb34dd05/token
  gateway_url: https://gateway.decapbridge.com

  # See who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}>
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}>
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}>
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}>
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}>
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}>

# Enable PKCE fields (optional, recommended)
auth:
  email_claim: email

# Add site links in Decap CMS (optional)
site_url: https://queeromaha.net

# Enable for local testing with `bunx decap-server`
local_backend: true

media_folder: img
public_folder: /

collections:
  - name: pages
    label: Pages
    files:
      - label: Home
        name: home
        file: src/home.md
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: Layout,
              name: layout,
              widget: hidden,
              default: layouts/base.njk,
            }
          - { label: Public, name: public, widget: boolean, default: true }
          - label: Items
            name: items
            widget: list
            types:
              - label: Section Header
                name: section
                fields:
                  - { label: Label, name: label, widget: string }
                  - { label: Anchor ID, name: id, widget: string }
                  - {
                      label: Note,
                      name: note,
                      widget: markdown,
                      required: false,
                    }
              - label: Item
                name: item
                fields:
                  - { label: Name, name: name, widget: string }
                  - {
                      label: Public,
                      name: public,
                      widget: boolean,
                      default: true,
                    }
                  - label: Tags
                    name: tags
                    widget: select
                    multiple: true
                    required: false
                    options:
                      - {
                          label: "🚻 Gender-neutral Bathroom",
                          value: "neutral-bathrooms",
                        }
                      - { label: "🛋️ Seating Available", value: "seating" }
                      - { label: "💻 Work/Study Spot", value: "work-spot" }
                      - { label: "🏳️‍🌈 Queer Owned", value: "queer-owned" }
                  - {
                      label: Description,
                      name: description,
                      widget: markdown,
                      required: false,
                    }
                  - label: Links
                    name: links
                    widget: list
                    required: false
                    fields:
                      - { label: Label, name: label, widget: string }
                      - { label: URL, name: url, widget: string }
                  - { label: Notes, name: notes, widget: text, required: false }
          - { label: Page Notes, name: notes, widget: text, required: false }

      - label: Art Events & Venues
        name: art
        file: src/art.md
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: Layout,
              name: layout,
              widget: hidden,
              default: layouts/base.njk,
            }
          - { label: Public, name: public, widget: boolean, default: true }
          - label: Items
            name: items
            widget: list
            types:
              - label: Section Header
                name: section
                fields:
                  - { label: Label, name: label, widget: string }
                  - { label: Anchor ID, name: id, widget: string }
                  - {
                      label: Note,
                      name: note,
                      widget: markdown,
                      required: false,
                    }
              - label: Item
                name: item
                fields:
                  - { label: Name, name: name, widget: string }
                  - {
                      label: Public,
                      name: public,
                      widget: boolean,
                      default: true,
                    }
                  - label: Tags
                    name: tags
                    widget: select
                    multiple: true
                    required: false
                    options:
                      - {
                          label: "🚻 Gender-neutral Bathroom",
                          value: "neutral-bathrooms",
                        }
                      - { label: "🛋️ Seating Available", value: "seating" }
                      - { label: "💻 Work/Study Spot", value: "work-spot" }
                      - { label: "🏳️‍🌈 Queer Owned", value: "queer-owned" }
                  - {
                      label: Description,
                      name: description,
                      widget: markdown,
                      required: false,
                    }
                  - label: Links
                    name: links
                    widget: list
                    required: false
                    fields:
                      - { label: Label, name: label, widget: string }
                      - { label: URL, name: url, widget: string }
                  - { label: Notes, name: notes, widget: text, required: false }
          - { label: Page Notes, name: notes, widget: text, required: false }

      - label: Music Events & Venues
        name: music
        file: src/music.md
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: Layout,
              name: layout,
              widget: hidden,
              default: layouts/base.njk,
            }
          - { label: Public, name: public, widget: boolean, default: true }
          - label: Items
            name: items
            widget: list
            types:
              - label: Section Header
                name: section
                fields:
                  - { label: Label, name: label, widget: string }
                  - { label: Anchor ID, name: id, widget: string }
                  - {
                      label: Note,
                      name: note,
                      widget: markdown,
                      required: false,
                    }
              - label: Item
                name: item
                fields:
                  - { label: Name, name: name, widget: string }
                  - {
                      label: Public,
                      name: public,
                      widget: boolean,
                      default: true,
                    }
                  - label: Tags
                    name: tags
                    widget: select
                    multiple: true
                    required: false
                    options:
                      - {
                          label: "🚻 Gender-neutral Bathroom",
                          value: "neutral-bathrooms",
                        }
                      - { label: "🛋️ Seating Available", value: "seating" }
                      - { label: "💻 Work/Study Spot", value: "work-spot" }
                      - { label: "🏳️‍🌈 Queer Owned", value: "queer-owned" }
                  - {
                      label: Description,
                      name: description,
                      widget: markdown,
                      required: false,
                    }
                  - label: Links
                    name: links
                    widget: list
                    required: false
                    fields:
                      - { label: Label, name: label, widget: string }
                      - { label: URL, name: url, widget: string }
                  - { label: Notes, name: notes, widget: text, required: false }
          - { label: Page Notes, name: notes, widget: text, required: false }

      - label: Cafes
        name: cafes
        file: src/cafes.md
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: Layout,
              name: layout,
              widget: hidden,
              default: layouts/base.njk,
            }
          - { label: Public, name: public, widget: boolean, default: true }
          - label: Items
            name: items
            widget: list
            types:
              - label: Section Header
                name: section
                fields:
                  - { label: Label, name: label, widget: string }
                  - { label: Anchor ID, name: id, widget: string }
                  - {
                      label: Note,
                      name: note,
                      widget: markdown,
                      required: false,
                    }
              - label: Item
                name: item
                fields:
                  - { label: Name, name: name, widget: string }
                  - {
                      label: Public,
                      name: public,
                      widget: boolean,
                      default: true,
                    }
                  - label: Tags
                    name: tags
                    widget: select
                    multiple: true
                    required: false
                    options:
                      - {
                          label: "🚻 Gender-neutral Bathroom",
                          value: "neutral-bathrooms",
                        }
                      - { label: "🛋️ Seating Available", value: "seating" }
                      - { label: "💻 Work/Study Spot", value: "work-spot" }
                      - { label: "🏳️‍🌈 Queer Owned", value: "queer-owned" }
                  - {
                      label: Description,
                      name: description,
                      widget: markdown,
                      required: false,
                    }
                  - label: Links
                    name: links
                    widget: list
                    required: false
                    fields:
                      - { label: Label, name: label, widget: string }
                      - { label: URL, name: url, widget: string }
                  - { label: Notes, name: notes, widget: text, required: false }
          - { label: Page Notes, name: notes, widget: text, required: false }

      - label: Makers
        name: makers
        file: src/makers.md
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: Layout,
              name: layout,
              widget: hidden,
              default: layouts/base.njk,
            }
          - { label: Public, name: public, widget: boolean, default: true }
          - label: Items
            name: items
            widget: list
            types:
              - label: Section Header
                name: section
                fields:
                  - { label: Label, name: label, widget: string }
                  - { label: Anchor ID, name: id, widget: string }
                  - {
                      label: Note,
                      name: note,
                      widget: markdown,
                      required: false,
                    }
              - label: Maker
                name: item
                fields:
                  - { label: Name, name: name, widget: string }
                  - {
                      label: Public,
                      name: public,
                      widget: boolean,
                      default: true,
                    }
                  - {
                      label: Description,
                      name: description,
                      widget: markdown,
                      required: false,
                    }
                  - label: Links
                    name: links
                    widget: list
                    required: false
                    fields:
                      - { label: Label, name: label, widget: string }
                      - { label: URL, name: url, widget: string }
                  - { label: Notes, name: notes, widget: text, required: false }
          - { label: Page Notes, name: notes, widget: text, required: false }

      - label: About
        name: about
        file: src/about.md
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: Layout,
              name: layout,
              widget: hidden,
              default: layouts/base.njk,
            }
          - { label: Public, name: public, widget: boolean, default: true }
          - { label: Body, name: body, widget: markdown }
          - { label: Page Notes, name: notes, widget: text, required: false }

      - label: Contact
        name: contact
        file: src/contact.md
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: Layout,
              name: layout,
              widget: hidden,
              default: layouts/base.njk,
            }
          - { label: Public, name: public, widget: boolean, default: true }
          - { label: Body, name: body, widget: markdown }
          - { label: Page Notes, name: notes, widget: text, required: false }
